Controllers/DepartmentsController.cs
using HospitalSystem.Data;
using HospitalSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalSystem.Controllers
{
    public class DepartmentsController : Controller
    {
        HospitalContext db = new HospitalContext();
        // GET: Departments
        public ActionResult Index()
        {
            if (Session["UserRole"]?.ToString() != "Admin") return RedirectToAction("Login", "Account");

            var departments = db.Departments.ToList();
            return View(departments);
        }
        public ActionResult Create()
        {
            if (Session["UserRole"]?.ToString() != "Admin") return RedirectToAction("Login", "Account");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (Session["UserRole"]?.ToString() != "Admin") return RedirectToAction("Login", "Account");
            if (ModelState.IsValid)
            {
                if (db.Departments.Any(d => d.DepartmentName.ToLower() == department.DepartmentName.ToLower()))
                {
                    ViewBag.Error = "Bu isimde bir departman var.";
                    return View(department);
                }

                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (Session["UserRole"]?.ToString() != "Admin") return RedirectToAction("Login", "Account");

            var dept = db.Departments.Find(id);
            if (dept != null)
            {
                if (dept.Doctors.Any())
                {
                    TempData["Error"] = "Bu bölümde çalışan doktorlar var. Önce doktorları çıkarın!";
                    return RedirectToAction("Index");
                }

                db.Departments.Remove(dept);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Admin/AddDoctor.cshtml
@{
    ViewBag.Title = "Yeni Doktor Ekle";
}

<h2>Yeni Doktor Ekle (Admin Paneli)</h2>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}
@if (ViewBag.Success != null)
{
    <div class="alert alert-success">@ViewBag.Success</div>
}

@using (Html.BeginForm("AddDoctor", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <h4>Doktor Kimlik Bilgileri</h4>
            <div class="form-group">
                <label>Ad</label>
                <input type="text" name="user.FirstName" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Soyad</label>
                <input type="text" name="user.LastName" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Email</label>
                <input type="email" name="user.Email" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Şifre</label>
                <input type="password" name="user.PasswordHash" class="form-control" required />
            </div>

            <div class="form-group">
                <label>TC Kimlik No</label>
                <input type="text" name="user.TCKN" class="form-control" required maxlength="11" />
            </div>

            <div class="form-group">
                <label>Telefon</label>
                <input type="text" name="user.Phone" class="form-control" maxlength="11" placeholder="05xxxxxxxxx" />
            </div>
        </div>

        <div class="col-md-6">
            <h4>Mesleki Bilgiler</h4>
            <hr />

            <div class="form-group">
                <label>Poliklinik / Bölüm</label>
                @if (ViewBag.DepartmentList != null)
                {
                    @Html.DropDownList("doctor.DepartmentID", (SelectList)ViewBag.DepartmentList, "Bölüm Seçiniz", new { @class = "form-control", required = "required" })
                }
                else
                {
                    <div class="alert alert-warning">
                        Sistemde kayıtlı bölüm bulunamadı. Lütfen veritabanına bölüm ekleyin.
                    </div>
                }
            </div> <div class="form-group">
                <label>Uzmanlık Alanı (Branş)</label>
                <input type="text" name="doctor.Specialization" class="form-control" placeholder="Örn: Kardiyoloji Uzmanı" required />
            </div>

            <div class="form-group">
                <label>Diploma Numarası</label>
                <input type="text" name="doctor.LicenseNumber" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Özgeçmiş / Biyografi</label>
                <textarea name="doctor.Biography" class="form-control" rows="4"></textarea>
            </div>
        </div>
    </div>

    <div class="form-group" style="margin-top:20px;">
        <button type="submit" class="btn btn-success btn-lg btn-block">
            <i class="glyphicon glyphicon-floppy-disk"></i> Doktoru Kaydet
        </button>
    </div>
}

<div class="row" style="margin-top: 15px;">
    <div class="col-md-12 text-center">
        <a href="@Url.Action("Index", "Admin")" class="btn btn-default">
            <i class="glyphicon glyphicon-arrow-left"></i> Yönetim Paneline Dön
        </a>
    </div>
</div>

Views/Admin/Index.cshtml
@model IEnumerable<HospitalSystem.Models.Doctor>

@{
    ViewBag.Title = "Admin Paneli";
}

<div class="container" style="padding-top: 30px;">

    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header">Yönetim Paneli (Dashboard)</h2>
        </div>
    </div>

    <div class="row text-center">
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">Top. Doktor</div>
                <div class="panel-body">
                    <h3>@ViewBag.TotalDoctors</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-success">
                <div class="panel-heading">Top. Hasta</div>
                <div class="panel-body">
                    <h3>@ViewBag.TotalPatients</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-info">
                <div class="panel-heading">Top. Randevu</div>
                <div class="panel-body">
                    <h3>@ViewBag.TotalAppointments</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">Aktif Randevular</div>
                <div class="panel-body">
                    <h3>@ViewBag.ActiveAppointments</h3>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-6">
            <a href="@Url.Action("Index", "Departments")" class="btn btn-info">
                <i class="glyphicon glyphicon-th-list"></i> Bölümleri Yönet
            </a>
            <a href="@Url.Action("AddDoctor", "Admin")" class="btn btn-success">
                <i class="glyphicon glyphicon-plus"></i> Yeni Doktor Ekle
            </a>
        </div>

        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                <input type="text" id="txtSearch" class="form-control" placeholder="Doktor Ara (İsim veya Soyisim)..." />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3>Sisteme Son Eklenen Doktorlar</h3>

            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Ad Soyad</th>
                        <th>Email</th>
                        <th>Bölüm</th>
                        <th>Telefon</th>
                        <th style="width: 100px;">İşlemler</th>
                    </tr>
                </thead>
                <tbody id="tblDoctors">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.User.FirstName @item.User.LastName</td>
                            <td>@item.User.Email</td>
                            <td>@(item.Department != null ? item.Department.DepartmentName : "-")</td>
                            <td>@(item.User.Phone ?? "-")</td>
                            <td>
                                <a href="@Url.Action("DeleteDoctor", "Admin", new { id = item.UserID })"
                                   class="btn btn-danger btn-xs"
                                   onclick="return confirm('@item.User.FirstName @item.User.LastName isimli doktoru silmek istediğinize emin misiniz?');">
                                    <i class="glyphicon glyphicon-trash"></i> Sil
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <div id="noDataAlert" class="alert alert-warning" style="display:none;">
                Aradığınız kriterlere uygun doktor bulunamadı.
            </div>

        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {

            $("#txtSearch").on("keyup", function () {
                var searchText = $(this).val();

                if (searchText.length === 0) {
                    location.reload();
                    return;
                }

                $.ajax({
                    url: '/Admin/SearchDoctor',
                    type: 'GET',
                    data: { searchTerm: searchText },
                    dataType: 'json',
                    success: function (data) {
                        $("#tblDoctors").empty();
                        $("#noDataAlert").hide();

                        if (data && data.length > 0) {
                            $.each(data, function (index, item) {
                                var row = '<tr>' +
                                    '<td>' + item.FullName + '</td>' +
                                    '<td> - </td>' +
                                    '<td><span class="label label-info">' + item.Branch + '</span></td>' +
                                    '<td>' + item.Phone + '</td>' +
                                    '<td>' +
                                    '<a href="/Admin/DeleteDoctor/' + item.UserID + '" class="btn btn-danger btn-xs" onclick="return confirm(\'Silmek istediğinize emin misiniz?\');">' +
                                    '<i class="glyphicon glyphicon-trash"></i> Sil' +
                                    '</a>' +
                                    '</td>' +
                                    '</tr>';
                                $("#tblDoctors").append(row);
                            });
                        } else {
                            $("#noDataAlert").show();
                        }
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            });
        });
    </script>
}